spring:
  application:
    name: finance-application
  config:
    import: classpath:datasource.yml,base.yml,cache.yml
  security:
    user:
      name: admin
      password: 123456
server:
  port: 58888

springdoc:
  swagger-ui:
    path: /swagger-ui.html

