spring:
  redis:
    host: localhost         # Redis 主机地址
    port: 6379              # Redis 端口
    password:  # 如果 Redis 设置了密码
    database: 0             # Redis 数据库索引
    jedis:
      pool:
        max-active: 10      # 最大连接数
        max-idle: 5         # 最大空闲连接数
        min-idle: 1         # 最小空闲连接数
        max-wait: -1        # 最大等待时间，-1 表示不限制
    timeout: 2000           # Redis 超时时间（毫秒）