finance:
  redis:
    url: localhost  # fiance.redis.url - Redis 的地址 #首次启动前务必修改成你自己的
    port: 6379  # fiance.redis.port - Redis 的端口号 #首次启动前务必修改成你自己的
    password:  # fiance.redis.password - Redis 的密码 #首次启动前务必修改成你自己的