spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/finance_data?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: mazhen5255
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5        # 初始连接池大小
      min-idle: 5            # 最小空闲连接数
      max-active: 20         # 最大连接池大小
      max-wait: 60000        # 获取连接的最大等待时间（毫秒）
      validation-query: SELECT 1 FROM DUAL  # 用于检测连接是否有效
      test-on-borrow: true   # 每次从连接池获取连接时，检查连接是否有效
      test-while-idle: true  # 定期检测连接是否有效
      time-between-eviction-runs-millis: 60000  # 连接池的空闲连接回收时间
      min-evictable-idle-time-millis: 300000  # 连接最小空闲时间
      log-abandoned: true    # 打印 SQL 异常信息
      remove-abandoned: true # 丢弃异常连接

  mybatis-plus:
    mapper-locations: classpath:/mappers/**/*.xml
    type-aliases-package: cn.com.mz.app.finance.datasource.entity  # 配置实体类所在包
    global-config:
      db-config:
        id-type: auto      # 主键生成策略
        field-strategy: not_empty  # 字段策略
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 输出 SQL 日志
